### ISSUE TITLE
duo_conf.erb variables are out of scope

### ISSUE THREAD

**Issue by zajk** [duosecurity/puppet-duo_unix#15]
OS: Ubuntu 14.04
Puppet: 4.1.0

Following config isn't producing any output in erb template:
```puppet
class { 'duo_unix':
    usage      => 'login',
    ikey       => 'something',
    skey       => 'something',
    host       => 'something',
    manage_ssh => false,
    pushinfo   => 'yes',
    autopush   => 'yes',
    prompts    => '1'
}
```
```erb
[duo]
; Duo integration key
ikey=<%= @ikey %>

; Duo secret key
skey=<%= @skey %>

; Duo API host
host=<%= @host %>
```
Looks like variables used in erb template are out of scope from duo_unix class. A fix could be either using scope['param'] in erb template or passing the params to duo_unix::login class. I can provide a pull request for either in about couple of minutes.

**Comment by mschwager** [comment]
Should be fixed with #17.
