### ISSUE TITLE
Still active?

### ISSUE THREAD

**Issue by bastelfreak** [duosecurity/puppet-duo_unix#35]
Hi folks,

I just wanted to ask if this module is still actively maintained. There are several open PRs since a very long time, also there is no support for puppet 4 and puppet 5. If you're interested you can migrate the module to [Vox Pupuli](https://voxpupuli.org/). This is a collection of Puppet developers and users that maintain abandoned modules.  They could take care of the module, if you want you can still keep write access to the repo. They are available 24/7 in the #voxpupuli IRC channel on freenode.

**Comment by adrikim** [comment]
Hey Tim, thanks for the suggestion! Unfortunately, I don't think we'd be able to transfer ownership of the repo, even if we do keep write access. From #32:

> We greatly appreciate you contributing your time and effort to help us with this project. This transfer is definitely something we'd like to undertake, but we're having a difficult time coming up with a good way to do it. There are security concerns around transferring ownership of the project, which effectively gives arbitrary code execution, to someone not affiliated with Duo. Our users and customers would be hard-pressed to know that we've transferred ownership of a product out from under them.
